language: python
branches:
  only:
    - develop
    - master
python:
  - "2.7"
  - "3.3"
  - "3.4"
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
services:
  - redis-server
install:
  - "pip install pycrypto requests"
before_script:
  - echo 'http://localhost:62421' > ~/.pssst
  - export PYTHON=`which python2`
  - cd src/server
  - npm install
  - node start &
  - cd ..
  - sleep 10
script:
  - python src/cli/pssst_test.py
