language: python
branches:
  only:
    - develop
    - release
    - master
python:
  - "2.7"
  - "3.3"
services:
  - redis-server
install:
  - "pip install pycrypto requests"
before_script:
  - echo 'http://localhost:62421' > .pssst
  - echo '{"debug":0,"port":62421,"db":{"socket":6379,"number":0}}' > server/config/config.json
  - cd server
  - npm install
  - node server.js &
  - cd ..
  - sleep 3
script:
  - python app/cli/pssst_test.py
