language: python
branches:
  only:
    - master
python:
  - "3.4"
  - "2.7"
node_js:
  - "4.2"
services:
  - redis-server
install:
  - "pip install pycrypto requests"
before_script:
  - export PYTHON=`which python2`
  - cd src/server
  - nvm install 4.2
  - nvm use 4.2
  - npm install
  - npm start &
  - cd ../..
  - sleep 10
script:
  - cd test
  - cp ../src/cli/pssst.py .
  - ./pssst_test.py
sudo: false
