language: python
branches:
  only:
    - master
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
node_js:
  - "8.6"
services:
  - redis-server
install:
  - "pip install -r requirements.txt"
before_script:
  - export PYTHON=`which python2`
  - export DYNO="Travis CI"
  - nvm install 8.6
  - nvm use 8.6
  - npm install
  - npm start &
  - sleep 30
script:
  - ./pssst_test.py
sudo: false
