language: python
branches:
  only:
    - master
    - develop
python:
  - "3.4"
  - "3.3"
  - "2.7"
node_js:
  - "4.1"
  - "0.12"
  - "0.10"
  - "iojs"
services:
  - redis-server
install:
  - "pip install pycrypto requests"
before_script:
  - nvm use 4.1
  - node --version
  - echo 'http://localhost:62421' > ~/.pssst
  - export PYTHON=`which python2`
  - cd src/server
  - npm install
  - npm start &
  - cd ../..
  - sleep 30
script:
  - python src/cli/pssst_test.py
sudo: false
