language: python
branches:
  only:
    - develop
    - master
python:
  - "2.7"
  - "3.3"
services:
  - redis-server
install:
  - "pip install pycrypto requests"
  - "pip install ndg-httpsclient pyasn1 pyopenssl"
before_script:
  - echo 'http://localhost:62421' > .pssst
  - echo '{"debug":0,"port":62421,"deny":null,"db":{"source":6379,"number":0}}' > server/config/config.json
  - export PYTHON=`which python2`
  - cd server
  - npm install
  - node start.js &
  - cd ..
  - sleep 10
script:
  - python app/cli/pssst_test.py
