.\" Manpage for pssst.
.\" Contact christian@uhsat.de to correct errors or typos.
.TH man 1 "February 2016" "Pssst" "Pssst Manual"
.SH NAME
pssst \- Pssst CLI
.SH SYNOPSIS
pssst [option|command] [-|username:password@server] [receiver message...]
.SH DESCRIPTION
Pssst is a simple and secure way to exchange information.
.SH OPTIONS
.IP "-h, --help"
Show usage
.IP "-l, --license"
Show license
.IP "-v, --version"
Show version
.SH COMMANDS
.B create
.RS
Create user.
.RE
.B delete
.RS
Delete user.
.RE
.B pull
.RS
Pull messages.
.RE
.B push
.RS
Push message.
.RE
.SH FILES
.I ~/.pssst
.RS
Default user profile. See
.I README.md
for further details.
.RE
.I ~/.pssst.<user>
.RS
User specific data including own and cached keys.
.RE
.SH AUTHORS
Christian Uhsat <christian@uhsat.de>
